---
name: CI
on:
  pull_request:
  push:

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  test_go:
    name: Go tests
    runs-on: ubuntu-latest
    container:
      image: golang:1.24.1-alpine
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - run: go test ./...
